In [35]:
import warnings
warnings.simplefilter('ignore')

In [36]:
# Read the csv file into a pandas DataFrame

fla = pd.read_csv('Florida_2.csv')
fla.head()

,BorrName,BorrStreet,BorrCity,BorrState,BorrZip,BorrID,LoanStatus,GrossApproval,SBAGuarantee,PctOfGuarantee,...,NaicsCode,NaicsDescription,JobsSupported,DeliveryMethod,subpgmdesc,BankName,BankStreet,BankCity,BankState,BankZip
0,"TARCA, INC..",3754 NW 54TH STREET,MIAMI,FL,33142,308,CHGOFF,1900000,1425000,0.75,...,423120,Motor Vehicle Supplies and New Parts Merchant ...,5,OTH 7A,Guaranty,TotalBank,100 SE 2nd St,MIAMI,FL,33131
1,Around the Clock Fitness,1242 SW Pine Island.,Cape coral,FL,33991,8127,PIF,521800,469620,0.90,...,713990,All Other Amusement and Recreation Industries,20,PLP,Guaranty,"Newtek Small Business Finance, Inc.",1981 Marcus Avenue,LAKE SUCCESS,NY,11042
2,"Integrated Metering Systems, I","11701 South Belcher Road, Sui",Largo,FL,33773,4025,PIF,40800,34680,0.85,...,335311,"Power, Distribution, and Specialty Transformer...",23,PLP,Guaranty,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901
3,Loving Enterprises Inc and 2 P,7885 Boca Ciega Drive,SAINT PETERSBURG,FL,33706,7228,PIF,332000,249000,0.75,...,453220,"Gift, Novelty, and Souvenir Stores",21,PLP,Guaranty,"PNC Bank, National Association",222 Delaware Ave,WILMINGTON,DE,19801
4,Lawrence J. Roberts & Associat,249 Catalonia Avenue.,Coral gables,FL,33134,1508,EXEMPT,225000,112500,0.50,...,541110,Offices of Lawyers,3,SBA EXPRES,FA$TRK (Small Loan Express),TotalBank,100 SE 2nd St,MIAMI,FL,33131

In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data1 = pd.read_csv('Florida_5.csv')

data1.drop(data1.columns[[2]], axis=1, inplace=True)

data1.tail()

,BorrName,BorrID,GrossApproval,SBAGuarantee,PctOfGuarantee,InterestRate,TermMonths,ApprovalFiscalYear,ApprovalDate,DisbursementDate,...,Leverage,COFiscalYear,COAmount,PrinBalanceCollected,PctOfPrinColl,CODate,DaysRemainingAtCO,MonthsRemainingAtCO,NaicsCode,JobsSupported
15132,"Advanced Family Care, Inc.",17748,100000,50000,0.5000,7.75,84,2010,8/5/10,8/5/10,...,4.0,0,0,100000.0,1.0,0,0,0,621111,5
15133,"Arcila Radiology Consulting, P",17749,50000,25000,0.5000,9.75,84,2010,6/8/10,6/8/10,...,4.0,0,0,50000.0,1.0,0,0,0,621399,1
15134,"Blinc, Inc.",17750,1750000,1499925,0.8571,6.00,120,2010,5/24/10,8/1/10,...,4.0,0,0,1750000.0,1.0,0,0,0,325620,13
15135,"Ana M. Houston, Inc.",17751,20000,10000,0.5000,9.75,60,2010,4/30/10,5/1/10,...,4.0,0,0,20000.0,1.0,0,0,0,115116,3
15136,"Milner's, Inc.",17752,35000,17500,0.5000,9.75,84,2010,4/5/10,4/5/10,...,4.0,0,0,35000.0,1.0,0,0,0,561730,13

In [38]:
X = data1.iloc[:, :3].values
y = data1.iloc[:, 15].values